---
# Source: kubedb/templates/apiregistration.yaml
apiVersion: v1
kind: Secret
metadata:
  name: RELEASE-NAME-kubedb-apiserver-cert
  namespace: default
  labels:
    chart: "kubedb-0.12.0"
    app: "kubedb"
    release: "RELEASE-NAME"
    heritage: "Helm"
type: Opaque
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURZVENDQWttZ0F3SUJBZ0lSQU9DNGo2NnF3anZjL0U1R3Fpdm10blF3RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdIaGNOTWpBd09ETXdNRFV6TURNNVdoY05NekF3T0RJNE1EVXpNRE01V2pBZQpNUnd3R2dZRFZRUURFeE5TUlV4RlFWTkZMVTVCVFVVdGEzVmlaV1JpTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBdDV6RWF6ZEQ3R08rdjBSUXVaYlpBa0o1UlJlOWtnTDNPTXZTdEJoaGpIZVYKbXVLaytUOW1ja1l2TXo2VnVVZ0hQR0ZuMlpqQ1QwY29WVWRoK0tUamcwRVJ0OFFTcTZNa2VpaVByUk5IdXU0bgpjbFJFREdQVThmaFBzZ1l6R0k1N3pCdUlRcWxYcXBRb0puRXZNU25Xb2ZyWWdUalZtL1ZBUHo4TGVYNEltVDJ3CjFlTWJuNlN1UEJ1OHFkeDJnTTg4TFpWeFNOOGlEV05wUzBMOFV4bk10TDNWNXBvbnMySEgwS2Z3M01HbXRXWmIKcDZxY0hBNndvc3dOeXp0cGRTakN2a1BmekMybkJGOEZhWFdNRkNDMnp1d1ZtcWcwMWZ4Z3Y3T29FeklQR1ZYMwpocUlqV3FGSjBJS2NwRGVSa1p0R1ZhNXBGa094QXFMaVUySk9MMUoveFFJREFRQUJvNEdxTUlHbk1BNEdBMVVkCkR3RUIvd1FFQXdJRm9EQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRFZSMFQKQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JUNmJQOWR2UW04eWwxOSs3NnhxV04zRmZkb09qQkhCZ05WSFJFRQpRREErZ2h0U1JVeEZRVk5GTFU1QlRVVXRhM1ZpWldSaUxtUmxabUYxYkhTQ0gxSkZURVZCVTBVdFRrRk5SUzFyCmRXSmxaR0l1WkdWbVlYVnNkQzV6ZG1Nd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHUU5oMFRRQXN4czN3WVcKTUd5ZjltSDVrYjJMd1hxL2o3RnRCaGNWbXJ0STFqTThmeWlCT0c1L3hmTFJCS3ZZTFgzdk14dkNSY09yY3JGTApCaERsRHBIUzBxa3FaWHhkc0cwREZpTFlJNE5JeXBrbnJJd1RJRHBpYnV5R0lxYXdVbDJEbE1iNHd3dG1jSzhECkxUZG45Sm1qK1dOcEJFZXE4bE82VCtYWjBpOEJnTmlsaGp5d25HZEF1VWt2WVAyRHFnbnZvL2c4TTVlNHo3eEEKNVlpcHBuK3lvK281V1phUXJYTHBqQm5ncHJqWDErMWJKcXlJYkNWSURDNGRPNW5LU0Q1SmdUWjNaUytnckJmSQpTOU5BR0w0YjNFaENtVHAzUWJBNzA2SjA1SU55ZW9nMWw3NmNVVmJFUmJsTDltTkV0MndSVDljNE04ZE11b1FzCmVoK25DcG89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdDV6RWF6ZEQ3R08rdjBSUXVaYlpBa0o1UlJlOWtnTDNPTXZTdEJoaGpIZVZtdUtrCitUOW1ja1l2TXo2VnVVZ0hQR0ZuMlpqQ1QwY29WVWRoK0tUamcwRVJ0OFFTcTZNa2VpaVByUk5IdXU0bmNsUkUKREdQVThmaFBzZ1l6R0k1N3pCdUlRcWxYcXBRb0puRXZNU25Xb2ZyWWdUalZtL1ZBUHo4TGVYNEltVDJ3MWVNYgpuNlN1UEJ1OHFkeDJnTTg4TFpWeFNOOGlEV05wUzBMOFV4bk10TDNWNXBvbnMySEgwS2Z3M01HbXRXWmJwNnFjCkhBNndvc3dOeXp0cGRTakN2a1BmekMybkJGOEZhWFdNRkNDMnp1d1ZtcWcwMWZ4Z3Y3T29FeklQR1ZYM2hxSWoKV3FGSjBJS2NwRGVSa1p0R1ZhNXBGa094QXFMaVUySk9MMUoveFFJREFRQUJBb0lCQUFmWThtZ21yNGQ5NTl3aQozbFJnUnh3YW5UWS93b0ZvRVFyall6a0JSY0lNSmwrOVNoSEJETzdiWXc4TW9MZVBoWWVtSGhzbHRVQlFLVUFqCjBlTWZvUDJ1SFVTK1k1SGtZaDI2ZUJHTW5tYzE0SWU1WkVNblRTV2VXRUdpbERKN2ZIMEh2RFlsS0xNSXJBS2cKbWNTL0pnWThRMTZhZ0Q2dko3VE1UQUJBUzd2STNhS2NGNnM4ZHd5R3Y3RUx5SENwK1QrTHAvWXlLQjBtUVRTNwpvaklpNmI5L1k3MHI3Ny9KYm1Ka3NvUzNwV0xUbVptQUU4RjVqMzU3YkRrVlgyQVJnOUtJQ29sQ1FjOU5CU25VCmgwWVB0ODJUSXFPaWorT0l1Z3Bwd1RUT2RadnZ4anBRTC9OaXp6QkMwcUxFanNuQ1BxQjlhbGQ1TndQTGJUQk8KQlo4UDMyRUNnWUVBNWN0SWhVRnE1Z1JPTjlJcDkrNTdqN2VyUDE3bHpvWkVKd2w0WUFNUkhTN2tzajV5U1lLMQovbW1WbDVJNmJzRlZzd3UramlPN1BWTEs5UG8vNmFBc1RQR29Jb0dZNmhTNDhXc203U3IvRUdkTGNnbzIyMkVPCkZWbUxSbDJWNmdvYklQMHBYZUY1eGpvT3N6MHZYZHJOWnZBVy9DNkpSUXBNdTBjbGxIZTJFeWtDZ1lFQXpJMDcKeU1uZ3ZJVWthcUYwd2ZzZXczSG04eU56Zm93ZGZXUXJ4VjdVZ2xYeHRBTFpvK2VoRStnR0hCditIWDhydzZjeApmZmlTUGdaWXhjaFdOcXpJTVJDMTlzQ0FLdTBEaUtEV1ZZNm1kZkF0dkJSUEJ6RVBEWnBGcWNUK3VSV3ZGQ0UrCkVqR0ZtV3pHYzZGcWxhbGRzZENGV0NzZ3BqQTdBbXd2QmRlbFZ6MENnWUJUakhtdG1YOVlhakJXTTE5MitZcUwKVW1nOC9pL255d0YwZ0FqNFA2VTFTeHR6Z3lqaWVWZmFUR0ZMWHF0SUlac2JJaVlDWUJOdjFHNWVhNjVaTHhkcwpVbUNqU3lOaDJHNzF0OVBMWDFxbGlDanlLYXlRVHRWa0JjNlJvdTBpenRIV1NMV0ZvTGs1elZvUzZTZ1RvNzRTCnN6Qm9PRE5JbXRvVExXY0llQTRISVFLQmdRQy9uVTN6dWFrYzhGdzh4eUpvMUtUczBUWlhiVTR6clcyeW1MT28KSUQxU0d0QmdvSXJnVDR0RTZvVk9yNnBNVjJUWDB6YzVtakRraVcxL1dUdnAyOUZzcFFyUUsyUGswa0lOS3gyYwo2QlJuUnFhUkdUVXV0M1l5ZCtIcU51K20wZmxBRWlQalJ5Q3ZxSVgrcTZiOHE3dHBacnlDNjJPYVNuUDh3UHNMCnJnYmt3UUtCZ0FkT1JwMm1iUzNyVGJ6YTNhYkdEdXp6OFNWVzlVQ2poNEJXN242V2xPUXUxN0drdTZlVEZzZzkKTm56QjF0THA5YUMzcWY0dC92cTlOVDZuZEdPVUFhQzhCMURyNXlhUDRBdFd2WldaL1VRK3RHQVNqei9raVV1MApQK3YzNXZRN0h5TWhOd0UvKzhBK1hscXVoSVJYb2J1ejJ4NERlN29ObHh6azBjazd5endrCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
# Source: kubedb/templates/apiregistration.yaml
# to delegate authentication and authorization
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: RELEASE-NAME-kubedb-apiserver-auth-delegator
  labels:
    chart: "kubedb-0.12.0"
    app: "kubedb"
    release: "RELEASE-NAME"
    heritage: "Helm"
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: RELEASE-NAME-kubedb
  namespace: default
---
# Source: kubedb/templates/apiregistration.yaml
# to read the config for terminating authentication
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: RELEASE-NAME-kubedb-apiserver-extension-server-authentication-reader
  namespace: kube-system
  labels:
    chart: "kubedb-0.12.0"
    app: "kubedb"
    release: "RELEASE-NAME"
    heritage: "Helm"
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: RELEASE-NAME-kubedb
  namespace: default
---
# Source: kubedb/templates/apiregistration.yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.validators.kubedb.com
  labels:
    chart: "kubedb-0.12.0"
    app: "kubedb"
    release: "RELEASE-NAME"
    heritage: "Helm"
spec:
  group: validators.kubedb.com
  version: v1alpha1
  service:
    namespace: default
    name: RELEASE-NAME-kubedb
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lRYitrcXhvWmo2NGtzdVpiVVVzb1ViVEFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TURBNE16QXdOVE13TXpsYUZ3MHpNREE0TWpnd05UTXdNemxhTUEweApDekFKQmdOVkJBTVRBbU5oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF1MDNECkdLUzNkSWN3b0kvVVpQajRVSVBRaE52L0Nud1hTM0dqakJxS0dNeHFrNWVFRjVyQVFUWWJYWWpmTFR6QUJxZGMKZ2d4UXZFNXVjZHlmM3A4OXIxaTIzbVRVUTM0ZTlReVViSkdKdUhldTNFa2VMM1ozYnBlcVIwUzVMa0xNcEN4ego3OEJYSXVVcSsvc2NGNnV0Ti9wczVvT0Y5VkoycmZtcHlEaUpoV0phWE1Bei9hSzBwQ0NxcSsvYWovWjJPT3FMCmcxRWJ4ZUpkaWVEbytibE5mL0ZoOTVrTzNZcHpYeklFbVBsTU5wdnY3ODU3QmFSUnVZeG96dE9lMnpaZHNwTjkKdkwxaUowd21MRnJXWDhYUmp4V3Jlei8vOXpyVmVibGR2dVVQa0NXMHBrb0dRL05mbnQ2UXdEUGxJZnZnMEFtcwpQYjQwY21JVEtGOFRTR3I5eFFJREFRQUJvMkV3WHpBT0JnTlZIUThCQWY4RUJBTUNBcVF3SFFZRFZSMGxCQll3CkZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUUKRlBwcy8xMjlDYnpLWFgzN3ZyR3BZM2NWOTJnNk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVZ0SEJ0NmpZUAoyRkh0cUVLbVJkWFZlbWttZlMydXNkd0YzQ0JMeWJpWFFWSmk0UTlzUWVoQVNObkhUa0txa3ErRW1ETmpEb1MrCkFEZ0FYZWZCdGFzV2h6QXZNVGZxRmplRnlxaEtwRTNlOTh4QlJOOTJwV3RQSTV2cE9QN043QXJteG5DWGl3ZWYKQWdwUncwcWZ2Mkl1VDVDZ1VqUmVXdnFyaHRtYlQ2eVVCVVVUM0VVR0xvWkhiK0MzZWZ4ckVNZFFtdzRoV20zWgpxSFFqcVZIaEJuVXdVb0l3eFAwRUY3TFJYY2tWbjFHbDJ3YmY1aDhYY1kycTNCblkxWkV2WjZkTnJaVXdyT3pmClRzTE1Pc3lEWDMzTndUd2RlcitWaXdGWHdHdHN6ZHJ4Y1hnT0RyanNrbWRUelcvd3lUWkNGb2x2M1VzYlVEMi8KT0ppT3NBSWlld2Y3Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  groupPriorityMinimum: 10000
  versionPriority: 15
---
# Source: kubedb/templates/apiregistration.yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.mutators.kubedb.com
  labels:
    chart: "kubedb-0.12.0"
    app: "kubedb"
    release: "RELEASE-NAME"
    heritage: "Helm"
spec:
  group: mutators.kubedb.com
  version: v1alpha1
  service:
    namespace: default
    name: RELEASE-NAME-kubedb
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lRYitrcXhvWmo2NGtzdVpiVVVzb1ViVEFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TURBNE16QXdOVE13TXpsYUZ3MHpNREE0TWpnd05UTXdNemxhTUEweApDekFKQmdOVkJBTVRBbU5oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF1MDNECkdLUzNkSWN3b0kvVVpQajRVSVBRaE52L0Nud1hTM0dqakJxS0dNeHFrNWVFRjVyQVFUWWJYWWpmTFR6QUJxZGMKZ2d4UXZFNXVjZHlmM3A4OXIxaTIzbVRVUTM0ZTlReVViSkdKdUhldTNFa2VMM1ozYnBlcVIwUzVMa0xNcEN4ego3OEJYSXVVcSsvc2NGNnV0Ti9wczVvT0Y5VkoycmZtcHlEaUpoV0phWE1Bei9hSzBwQ0NxcSsvYWovWjJPT3FMCmcxRWJ4ZUpkaWVEbytibE5mL0ZoOTVrTzNZcHpYeklFbVBsTU5wdnY3ODU3QmFSUnVZeG96dE9lMnpaZHNwTjkKdkwxaUowd21MRnJXWDhYUmp4V3Jlei8vOXpyVmVibGR2dVVQa0NXMHBrb0dRL05mbnQ2UXdEUGxJZnZnMEFtcwpQYjQwY21JVEtGOFRTR3I5eFFJREFRQUJvMkV3WHpBT0JnTlZIUThCQWY4RUJBTUNBcVF3SFFZRFZSMGxCQll3CkZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUUKRlBwcy8xMjlDYnpLWFgzN3ZyR3BZM2NWOTJnNk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVZ0SEJ0NmpZUAoyRkh0cUVLbVJkWFZlbWttZlMydXNkd0YzQ0JMeWJpWFFWSmk0UTlzUWVoQVNObkhUa0txa3ErRW1ETmpEb1MrCkFEZ0FYZWZCdGFzV2h6QXZNVGZxRmplRnlxaEtwRTNlOTh4QlJOOTJwV3RQSTV2cE9QN043QXJteG5DWGl3ZWYKQWdwUncwcWZ2Mkl1VDVDZ1VqUmVXdnFyaHRtYlQ2eVVCVVVUM0VVR0xvWkhiK0MzZWZ4ckVNZFFtdzRoV20zWgpxSFFqcVZIaEJuVXdVb0l3eFAwRUY3TFJYY2tWbjFHbDJ3YmY1aDhYY1kycTNCblkxWkV2WjZkTnJaVXdyT3pmClRzTE1Pc3lEWDMzTndUd2RlcitWaXdGWHdHdHN6ZHJ4Y1hnT0RyanNrbWRUelcvd3lUWkNGb2x2M1VzYlVEMi8KT0ppT3NBSWlld2Y3Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  groupPriorityMinimum: 10000
  versionPriority: 15
