---
# Source: kubedb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kubedb
  namespace: flux
  labels:
    chart: "kubedb-0.12.0"
    app: "kubedb"
    release: "kubedb"
    heritage: "Helm"
spec:
  ports:
  - name: api
    port: 443
    targetPort: 8443
  selector:
    app: "kubedb"
    release: "kubedb"
