---
# Source: kubedb-catalog/templates/mongodb-psp.yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: mongodb-db
  labels:
    chart: "kubedb-catalog-0.12.0"
    app: "kubedb"
    release: "kubedb-catalog"
    heritage: "Helm"
spec:
  privileged: false
  allowPrivilegeEscalation: false
  volumes:
  - "*"
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
---
# Source: kubedb-catalog/templates/mongodb-psp.yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: mongodb-snapshot
  labels:
    chart: "kubedb-catalog-0.12.0"
    app: "kubedb"
    release: "kubedb-catalog"
    heritage: "Helm"
spec: #same spec as db
  privileged: false
  allowPrivilegeEscalation: false
  volumes:
  - "*"
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
